PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO sporten VALUES(10,'voetbal');
INSERT INTO sporten VALUES(20,'tennis');
INSERT INTO sporten VALUES(30,'hockey');
INSERT INTO sporten VALUES(40,'dammen');
INSERT INTO sporten VALUES(50,'schaken');
INSERT INTO personen VALUES(1,'Jan');
INSERT INTO personen VALUES(2,'Piet');
INSERT INTO personen VALUES(3,'Berke');
INSERT INTO personen_sporten VALUES(1,10);
INSERT INTO personen_sporten VALUES(1,20);
INSERT INTO personen_sporten VALUES(1,30);
INSERT INTO personen_sporten VALUES(2,40);
INSERT INTO personen_sporten VALUES(2,50);
INSERT INTO personen_sporten VALUES(3,10);
INSERT INTO personen_sporten VALUES(3,40);
INSERT INTO sqlite_sequence VALUES('personen',3);
COMMIT;
